### ISSUE TITLE
[Request] 게임에 대한 개발 진행 방향 공유

### ISSUE THREAD

**Issue by sang-kyeong** [42ft-transcendence/transcendence#101]
## 📃 Description

게임에 대한 백엔드를 jeongkpa님과 sehjung님이 나누어 진행함에 따라 개발 진행 방향으로 공유하려고 합니다.
jeongkpa : 게임 관리
sehjung: 게임 엔진
yje : 프론트

## Subject

이 웹사이트의 주요 목적은 다른 플레이어와 Pong 게임을 플레이하는 것입니다.

- 따라서 사용자는 웹사이트에서 직접 다른 플레이어와 실시간 Pong 게임을 플레이할 수 있어야 합니다.
- **매칭 시스템**이 있어야 합니다: 사용자는 대기열에 참여하여 자동으로 다른 사람과 매칭될 때까지 기다릴 수 있어야 합니다.
- 게임은 캔버스 게임이거나 3D로 렌더링된 게임이거나, 예쁘지 않을 수도 있지만, 어떤 경우에도 **오리지널 Pong**(1972)에 충실해야 합니다.
- 사용자에게 **사용자 정의 옵션**(예: 강화 아이템 또는 다른 맵)을 제공해야 합니다. 그러나 사용자는 원한다면 추가 기능 없이 기본 버전의 게임을 선택할 수 있어야 합니다.
- 게임은 **반응형**이어야 합니다!

> 💡예기치 않은 연결 끊김이나 지연과 같은 네트워크 문제에 대해 고려해야 합니다. 최상의 사용자 경험을 제공해야 합니다.

게임에 대한 결정 사항들을 자유롭게 공유 바랍니다.

**Comment by Jsen27** [comment]
마우스로 게임플레이 한다는 가정하에 패들속도에 비례해서 공의 속도를 조절하는 부분도 구현하겠습니다.
