### ISSUE TITLE
[Request] 2fa관련 기능 완성 요청

### ISSUE THREAD

**Issue by sang-kyeong** [42ft-transcendence/transcendence#95]
## 📃 Description

2fa 관련 기능에서 repository 함수가 아직 구현되지 않았습니다.
user.repository.ts 에서 2fa secret혹은 2fa enabled 를 수정하는 함수가 보이지 않습니다.

**Comment by Jsen27** [comment]
혹시 auth.controller.ts 에 있는 @Post('turn-on') 부분 말씀하시는 걸까요?

**Comment by sang-kyeong** [comment]
generate부터 500에러가 납니다
아예 userRepository를 인식할 수 없다고 하는데 다른 api에서는 잘 되구요
에러 내용이 도대체 무슨 소리인지 모르겠어서 오늘 예기하려 했어요

**Comment by sang-kyeong** [comment]
generate에서 에러가 나는 부분은 user.service에서 secret저장하는 부분의 user Repository부분입니다
